# Numpy - array

## outlines

* basic
* simple funtion
* saving and loading files

In [1]:
import numpy as np

## basic 

In [2]:
# create an array
arr = np.array([1,2,3])
print(arr)
print('1:\n',np.ones([5,5]))
print('2:\n',np.zeros([1,2,3,4]))
print('3:\n',np.eye(5))

[1 2 3]
1:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2:
 [[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]
3:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
# indexing array
a = np.arange(30).reshape(3,-1)
print(a)
print(a[1:,:3])

# choose more than one rows
b = np.arange(100).reshape(5,-1)
print(b)
b[[3,4,1]]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[10 11 12]
 [20 21 22]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

In [4]:
# array transform
a = np.arange(50).reshape(5,-1)
print(a.T)

# dot
print(np.dot(a,a.T))

[[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]
[[  285   735  1185  1635  2085]
 [  735  2185  3635  5085  6535]
 [ 1185  3635  6085  8535 10985]
 [ 1635  5085  8535 11985 15435]
 [ 2085  6535 10985 15435 19885]]


## simple funtion

In [5]:
# Array funtion
A = np.random.randn(10)
B = np.random.randn(10)
print('A is :'+'\n'+str(A))
print('B is :'+'\n'+str(B))

# binary funtion 
print(np.add(A,B))
print(np.maximum(A,B))

A is :
[ 0.20354644 -0.30715301  0.80021159  0.16731073  0.38143633 -0.73427443
 -0.75748425 -0.2357754   0.18487482  0.89338238]
B is :
[-0.74578361  0.74406298  0.0282252  -0.01131237  0.32851195 -2.13836711
  0.07473944 -1.96499815  1.08330105  1.70096222]
[-0.54223717  0.43690997  0.82843679  0.15599837  0.70994828 -2.87264154
 -0.68274482 -2.20077355  1.26817586  2.59434459]
[ 0.20354644  0.74406298  0.80021159  0.16731073  0.38143633 -0.73427443
  0.07473944 -0.2357754   1.08330105  1.70096222]


In [6]:
# numpy where
a = np.array([1,2,3,4])
b = np.array([500,600,700,800])
condition = np.array([True,False,True,False])

answer = [(a_v if cond else b_v) for a_v,b_v,cond in zip(a,b,condition)]
print(answer)

# 
answer2 = np.where(condition,a,b)
answer2

[1, 600, 3, 800]


array([  1, 600,   3, 800])

In [7]:
# condition
a = np.random.randn(5,5)
answer = np.where(a>0,0,a)
answer

array([[-0.29862836, -0.52619262, -2.03959888,  0.        , -1.12859989],
       [-0.71767299, -0.65538342, -1.92824942, -0.08382187,  0.        ],
       [ 0.        , -1.8210308 ,  0.        ,  0.        , -0.08498949],
       [-1.07116682, -0.25441271,  0.        ,  0.        ,  0.        ],
       [-1.08585896, -0.51298524,  0.        ,  0.        , -0.26352454]])

In [8]:
# sum 
a = np.arange(1,13).reshape(3,-1)
print(a)
print('1:',a.sum())
print('2:',a.sum(0))
print('3:',a.sum(1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1: 78
2: [15 18 21 24]
3: [10 26 42]


In [9]:
# np.unique
fruit = np.array(['apple','bannana','lemon','apple'])
print(np.unique(fruit))
np.in1d(['apple','lemon','orange'],fruit)

['apple' 'bannana' 'lemon']


array([ True,  True, False])

## saving and loading files

In [10]:
# save
arr = np.arange(5)
np.save('my_array_0509',arr)

# load
arr1 = np.load('my_array_0509.npy')
arr1

array([0, 1, 2, 3, 4])

In [11]:
arr = np.arange(5)
arr1 = np.arange(10)
np.savez('two_arrays.npz',x=arr,y=arr1)
arr_ = np.load('two_arrays.npz')
print(arr_['x'])
arr_['y']

[0 1 2 3 4]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#saving and loading text files
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])